/*NOME:MATHEUS ABILIO DA SILVA CAMARGO RA:841929 */
/*EX 1*/
CREATE USER EXERCICIO_841929
IDENTIFIED BY 123456
TABLESPACE DEFAULT
TEMPORARY TABLESPACE TEMP;

/*EX 2*/
CREATE TABLE CONDOMINIO (
    COD_CONDOMINIO INTEGER,
    NOM_CONDOMINIO VARCHAR2(40) NOT NULL,
    CNPJ_CONDOMINIO VARCHAR(14) NOT NULL,
    END_CONDOMINIO VARCHAR(40) NOT NULL,
    BAI_CONDOMINIO VARCHAR(25) NOT NULL,
    CEP_CONDOMINIO VARCHAR(8) NOT NULL,
    CID_CONDOMINIO VARCHAR(35),
    UF_CONDOMINIO CHAR(2) NOT NULL,
    CONSTRAINT PK_CONDOMINIO PRIMARY KEY (COD_CONDOMINIO)
);

CREATE TABLE APARTAMENTO (
    NUM_APARTAMENTO NUMERIC(4),
    COD_CONDOMINIO INTEGER,
    NOM_RESPONS_APARTAMENTO VARCHAR(40) NOT NULL,
    RG_RESPONS_APARTAMENTO VARCHAR(12) NOT NULL,
    CPF_RESPONS_APARTAMENTO VARCHAR(14) NOT NULL,
    DTN_RESPONS_APARTAMENTO DATE,
    CONSTRAINT PK_APARTAMENTO PRIMARY KEY (NUM_APARTAMENTO, COD_CONDOMINIO),
    CONSTRAINT FK_APARTAMENTO_CONDOMINIO FOREIGN KEY (COD_CONDOMINIO) REFERENCES CONDOMINIO(COD_CONDOMINIO)
);

CREATE TABLE TELEFONE (
    DDD_TELEFONE VARCHAR(2),
    NUM_TELEFONE VARCHAR(10),
    COD_CONDOMINIO INTEGER,
    NUM_APARTAMENTO NUMERIC(4),
    CONSTRAINT PK_TELEFONE PRIMARY KEY (DDD_TELEFONE, NUM_TELEFONE, COD_CONDOMINIO, NUM_APARTAMENTO),
    CONSTRAINT FK_TELEFONE_CONDOMINIO_APARTAMENTO FOREIGN KEY (COD_CONDOMINIO, NUM_APARTAMENTO) REFERENCES APARTAMENTO(COD_CONDOMINIO, NUM_APARTAMENTO)
);

CREATE TABLE BANCO (
    COD_BANCO INTEGER,
    NOM_BANCO VARCHAR(30),
    CONSTRAINT PK_BANCO PRIMARY KEY (COD_BANCO)
);

CREATE TABLE CONTA_CORRENTE (
    NUM_CC VARCHAR(8) NOT NULL,
    NUM_AGENCIA_CC VARCHAR(6) NOT NULL,
    BANCO_COD_BANCO INTEGER NOT NULL,
    NOM_GERENTE_CC VARCHAR(35),
    COD_CONDOMINIO INTEGER,
    CONSTRAINT PK_CC PRIMARY KEY (NUM_CC, NUM_AGENCIA_CC),
    CONSTRAINT FK_CC_BANCO FOREIGN KEY (BANCO_COD_BANCO) REFERENCES BANCO(COD_BANCO)
);

/* EX 3 */
ALTER TABLE CONTA_CORRENTE ADD COLUMN DTA_ABERTA_CC DATE;
ALTER TABLE CONTA_CORRENTE ADD COLUMN VLR_LIMITE_CC NUMBER (10,2);

/* EX 4 */

INSERT INTO CONDOMINIO VALUES (1,'Versailles','15151414131312','Rua Jardim boa vista n:103','Boa vista','14079432','Ribeirão Preto','SP'),
(2,'TheTown','20201919181817','Rua coronel xavier n:15','Centro','18465810','Aguas Claras','MG');

INSERT INTO APARTAMENTO VALUES (508,1,'Matheus Abilio','559800801','44845147382','1988-08-20'),
(702,2,'Gustavo Silva','547902820','45835147345','2000-03-11');

INSERT INTO TELEFONE VALUES ('16','988307356',1,508),
('31','984561278',2,702);

INSERT INTO BANCO VALUES (1,'Itau'),
(2,'Bradesco');

INSERT INTO CONTA_CORRENTE ('20042004','203',1,'Ricardo Silva',1),
('20302030','108',2,'Alexandre Costa',2);

/* EX 5 */

UPDATE APARTAMENTO SET NOM_RESPONS_APARTAMENTO = UPPER(NOM_RESPONS_APARTAMENTO)
WHERE NOM_RESPONS_APARTAMENTO LIKE '%SILVA%';

/* EX 6 */

SELECT AP.NUM_APARTAMENTO, AP.NOM_RESPONS_APARTAMENTO, AP.CPF_RESPONS_APARTAMENTO, TL.NUM_TELEFONE, TL.DDD_TELEFONE FROM APARTAMENTO AP
INNER JOIN TELEFONE TL ON AP.NUM_APARTAMENTO = TL.NUM_APARTAMENTO;

/* EX 7 */

SELECT AP.COD_CONDOMINIO, CO.NOME_CONDOMINIO, COUNT(AP.NUM_APARTAMENTO) AS QUANTIDADE_APARTAMENTOS
FROM APARTAMENTO AP INNER JOIN CONDOMINIO CO ON AP.COD_CONDOMINIO = CO.COD_CONDOMINIO GROUP BY AP.COD_CONDOMINIO, CO.NOME_CONDOMINIO;

/* EX 8 */

SELECT CO.COD_CONDOMINIO, CO.NOME_CONDOMINIO, COUNT(AP.NUM_APARTAMENTO) AS QUANTIDADE_APARTAMENTOS
FROM CONDOMINIO CO INNER JOIN APARTAMENTO AP ON CO.COD_CONDOMINIO = AP.COD_CONDOMINIO GROUP BY CO.COD_CONDOMINIO, CO.NOME_CONDOMINIO 
ORDER BY QUANTIDADE_APARTAMENTOS DESC LIMIT 10;


